2024-12-12 15:17:59,582 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "F:\PYTHON\Project\Lesson_12\main\tests_12_4.py", line 22, in test_run
    r2 = Runner(2)
         ^^^^^^^^^
  File "F:\PYTHON\Project\Lesson_12\main\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-12 15:17:59,583 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "F:\PYTHON\Project\Lesson_12\main\tests_12_4.py", line 12, in test_walk
    r1 = Runner('Tom', -5)
         ^^^^^^^^^^^^^^^^^
  File "F:\PYTHON\Project\Lesson_12\main\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
